#cloud-config
disk_setup:
  ephemeral0:
    table_type: mbr
    layout: [33, [66, 82]] # 33% (400 GB of the 600 GB will be mounted as swap space for tmpfs)
    overwrite: True
fs_setup:
  - device: ephemeral0.1
    filesystem: ext4
  - device: ephemeral0.2
    filesystem: swap
mounts:
  - ["ephemeral0.1", "/azure/resource"]
  - ["ephemeral0.2", "none", "swap", "sw,nofail,x-systemd.requires=cloud-init.service,x-systemd.device-timeout=2", "0", "0"]